# SPDX-FileCopyrightText: 2023 Gottlieb+Freitag <info@gottliebtfreitag.de>
# SPDX-License-Identifier: CC0-1.0
name: "Linux"

on:
  push:
    branches:
      - 'main'
  pull_request:

concurrency:
  group: linux-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: ${{ matrix.compiler }}
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - gcc13-cpp20-release
          - gcc12-cpp20-release
          - gcc11-cpp20-release
          - gcc13-cpp20-debug-sanitize_address
          - gcc13-cpp20-debug-sanitize_undefined
          - gcc13-cpp20-lcov-cpm_check_version
          - clang17-cpp20-release
    steps:
      - name: Standard IV-project testing
        uses: iv-project/IVaction/linux-testing@feat/cpm/version_checkv3
        with:
          compiler: ${{ matrix.compiler }}
          threads: 2
          cov_secret: ${{ secrets.CODECOV_TOKEN }}
