# SPDX-FileCopyrightText: 2023 Gottlieb+Freitag <info@gottliebtfreitag.de>
# SPDX-License-Identifier: CC0-1.0
name: REUSE Compliance Check

on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

jobs:
  license_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: REUSE Compliance Check
      uses: fsfe/reuse-action@v2
      with:
        args: --suppress-deprecation lint
