# SPDX-FileCopyrightText: 2023 Gottlieb+Freitag <info@gottliebtfreitag.de>
# SPDX-License-Identifier: CC0-1.0
name: "MacOS"

on:
  push:
    branches:
      - 'main'
  pull_request:

concurrency:
  group: macos-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: ${{ matrix.compiler }}
    runs-on: macos-12
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - clang17-cpp20-release
    steps:
      - name: Standard IV-project testing
        uses: iv-project/IVaction/macos-testing@v6.2
        with:
          compiler: ${{ matrix.compiler }}
          threads: 3
