# SPDX-FileCopyrightText: 2023 Gottlieb+Freitag <info@gottliebtfreitag.de>
# SPDX-License-Identifier: CC0-1.0
name: "Windows Server 2022"

on:
  push:
    branches:
      - 'main'
  pull_request:

concurrency:
  group: msvc-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Windows Server 2022
    runs-on: windows-2022
    timeout-minutes: 120
    steps:
      - name: Standard IV-project testing
        uses: iv-project/IVaction/msvc-testing@v6.2
