# SPDX-FileCopyrightText: 2006-2023, Knut Reinert & Freie Universität Berlin
# SPDX-FileCopyrightText: 2016-2023, Knut Reinert & MPI für molekulare Genetik
# SPDX-License-Identifier: CC0-1.0
name: "Weekly CI"

on:
  schedule:
    - cron: '0 5 * * Mon'
  workflow_dispatch:
env:
  TZ: Europe/Berlin

concurrency:
  group: weekly
  cancel-in-progress: true

jobs:
  build:
    name: ${{ matrix.os }}-${{ matrix.compiler }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        include:
          - {os: ubuntu-22.04, compiler: spdx_license_lint}
          - {os: ubuntu-22.04, compiler: gcc14-cpp20-release}
    steps:
      - name: Standard IV-project testing
        uses: iv-project/IVaction@v9.20
        with:
          compiler: ${{ matrix.compiler }}
          threads: 2
          cmake_flags: ${{ matrix.cmake_flags }}
      - name: Open Issue
        uses: jayqi/failed-build-issue-action@v1.2.0
        if: failure()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
