# SPDX-FileCopyrightText: 2023 Gottlieb+Freitag <info@gottliebtfreitag.de>
# SPDX-License-Identifier: CC0-1.0
name: "CI"

on:
  push:
    branches:
      - 'main'
  pull_request:

env:
  TZ: Europe/Berlin

concurrency:
  group: ${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  license_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: REUSE Compliance Check
      uses: fsfe/reuse-action@v2
      with:
        args: --suppress-deprecation lint
  linux:
    name: linux-${{ matrix.compiler }}
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - gcc13-cpp20-release
          - gcc12-cpp20-release
          - gcc11-cpp20-release
          - gcc13-cpp20-debug-sanitize_address
          - gcc13-cpp20-debug-sanitize_undefined
          - gcc13-cpp20-lcov-cpm_check_version
          - clang17-cpp20-release
    steps:
      - name: Standard IV-project testing
        uses: iv-project/IVaction/linux-testing@v8.2
        with:
          compiler: ${{ matrix.compiler }}
          threads: 2
          cov_secret: ${{ secrets.CODECOV_TOKEN }}
  macos:
    name: macos-${{ matrix.compiler }}
    runs-on: macos-12
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - gcc13-cpp20-release
          - clang17-cpp20-release
    steps:
      - name: Standard IV-project testing
        uses: iv-project/IVaction/macos-testing@v8.2
        with:
          compiler: ${{ matrix.compiler }}
          threads: 3
